version: '3'

services:
  master:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8089:8089"
    volumes:
      - ./:/app
    command: -f /app/locustfile.py --master -H http://master:8089 --web-auth='${HTUSER}:${HTPASSWD}'

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: -f /app/locustfile.py --worker --master-host master --web-auth='${HTUSER}:${HTPASSWD}'
